{
    "cells": [
        {
            "cell_type": "code",
            "execution_count": null,
            "id": "52927ce1",
            "metadata": {"vscode": {"languageId": "plaintext"}},
            "outputs": [],
            "source": [
                "####\n",
                "\n",
                "#### 학습\n",
                "\n",
                "import os\n",
                "import glob\n",
                "import random\n",
                "import argparse\n",
                "import logging\n",
                "import sys\n",
                "import csv\n",
                "from typing import List\n",
                "\n",
                "import numpy as np\n",
                "import cv2\n",
                "from sklearn.model_selection import train_test_split\n",
                "\n",
                "import torch\n",
                "import torch.nn as nn\n",
                "import torch.nn.functional as F\n",
                "import torch.optim as optim\n",
                "from torch.nn.utils.parametrizations import weight_norm\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "from torchvision import transforms\n",
                "from pytorch_metric_learning import losses\n",
                "from torch.utils.data.dataloader import default_collate\n",
                "from tqdm.auto import tqdm\n",
                "import concurrent.futures\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# Logging\n",
                "# ==============================================================================\n",
                "logging.basicConfig(\n",
                "    level=logging.INFO,\n",
                '    format="%(asctime)s | %(levelname)s | %(message)s",\n',
                '    datefmt="%Y-%m-%d %H:%M:%S",\n',
                ")\n",
                "logger = logging.getLogger(__name__)\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# 0. User Configuration (HARDCODED FOR COLAB)\n",
                "# ==============================================================================\n",
                "DEFAULT_DATA_ROOTS = {\n",
                '    "Control": [\n',
                '        "/content/Control_C4/",\n',
                '        "/content/Control_C18/",\n',
                '        "/content/Control_C19/",\n',
                "    ],\n",
                '    "SNCA": ["/content/SNCA/"],\n',
                '    "GBA": ["/content/GBA/"],\n',
                '    "PINK1": ["/content/PINK1/"],\n',
                "}\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# 1. Configuration & Reproducibility\n",
                "# ==============================================================================\n",
                "def get_args():\n",
                '    parser = argparse.ArgumentParser(description="SupCon Training for 16-bit Biological Images")\n',
                "\n",
                "    # Experiment\n",
                '    parser.add_argument("--seed", type=int, default=42, help="Random seed")\n',
                '    parser.add_argument("--save_dir", type=str, default="/content/drive/MyDrive/Final_paper/Model2", help="Save directory")\n',
                "\n",
                "    # Data\n",
                '    parser.add_argument("--max_samples", type=int, default=18000, help="Max samples per class")\n',
                '    parser.add_argument("--test_ratio", type=float, default=1 / 3, help="Test split ratio")\n',
                '    parser.add_argument("--val_ratio", type=float, default=0.25, help="Validation split ratio")\n',
                "\n",
                "    # Training\n",
                '    parser.add_argument("--img_size", type=int, default=128, help="Input image size")\n',
                '    parser.add_argument("--batch_size", type=int, default=256, help="Batch size")\n',
                '    parser.add_argument("--epochs", type=int, default=100, help="Number of epochs")\n',
                '    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate")\n',
                '    parser.add_argument("--temp", type=float, default=0.1, help="Temperature for SupCon loss")\n',
                '    parser.add_argument("--embed_dim", type=int, default=512, help="Projection head dimension")\n',
                '    parser.add_argument("--patience", type=int, default=10, help="Early stopping patience")\n',
                "\n",
                "    # Jupyter/Colab\n",
                '    if "ipykernel" in sys.modules:\n',
                "        return parser.parse_args([])\n",
                "    return parser.parse_args()\n",
                "\n",
                "\n",
                "def set_seed(seed: int):\n",
                "    random.seed(seed)\n",
                "    np.random.seed(seed)\n",
                "    torch.manual_seed(seed)\n",
                "    torch.cuda.manual_seed_all(seed)\n",
                "\n",
                "    # Speed mode (non-deterministic)\n",
                "    torch.backends.cudnn.deterministic = False\n",
                "    torch.backends.cudnn.benchmark = True\n",
                "\n",
                '    logger.info(f"Random Seed set to {seed}")\n',
                '    logger.info(f"cudnn.deterministic={torch.backends.cudnn.deterministic}, cudnn.benchmark={torch.backends.cudnn.benchmark}")\n',
                "\n",
                "\n",
                "def seed_worker(worker_id: int):\n",
                "    worker_seed = torch.initial_seed() % 2**32\n",
                "    np.random.seed(worker_seed)\n",
                "    random.seed(worker_seed)\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# Data validation & collate\n",
                "# ==============================================================================\n",
                "def validate_uint16_rgb_128(img: np.ndarray, filepath: str, img_size: int = 128):\n",
                "    if img is None:\n",
                '        raise ValueError("cv2.imread returned None")\n',
                "    if img.dtype != np.uint16:\n",
                '        raise ValueError(f"dtype must be uint16, got {img.dtype}")\n',
                "    if img.ndim != 3 or img.shape[2] != 3:\n",
                '        raise ValueError(f"shape must be HxWx3, got {img.shape}")\n',
                "    h, w = img.shape[:2]\n",
                "    if (h, w) != (img_size, img_size):\n",
                '        raise ValueError(f"size must be {(img_size, img_size)}, got {(h, w)}")\n',
                "\n",
                "\n",
                "def log_skip(filepath: str, reason: Exception):\n",
                '    print(f"[DATA_SKIP] {filepath} | {type(reason).__name__}: {reason}", file=sys.stderr, flush=True)\n',
                "\n",
                "\n",
                "def collate_skip_none(batch):\n",
                "    batch = [b for b in batch if b is not None]\n",
                "    if len(batch) == 0:\n",
                "        return None\n",
                "    return default_collate(batch)\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# 2. Preprocessing & Dataset\n",
                "# ==============================================================================\n",
                "class SafeInstanceNormalize:\n",
                '    """(x - mu) / max(std, threshold) on CHW tensor."""\n',
                "    def __init__(self, threshold: float = 0.01):\n",
                "        self.threshold = float(threshold)\n",
                "\n",
                "    def __call__(self, tensor: torch.Tensor) -> torch.Tensor:\n",
                "        mean = torch.mean(tensor, dim=[1, 2], keepdim=True)\n",
                "        std = torch.std(tensor, dim=[1, 2], keepdim=True)\n",
                "        std = std.clamp_min(self.threshold)\n",
                "        return (tensor - mean) / std\n",
                "\n",
                "\n",
                "class InMemorySixteenBitDataset(Dataset):\n",
                '    """\n',
                "    - uint16 TIFF (128x128x3) -> float32 [0,1] -> CHW tensor\n",
                "    - two_crops: return (view1, view2, label)\n",
                "    - augment: rotation aug ON/OFF\n",
                "    - preloaded_images: reuse RAM cache\n",
                '    """\n',
                "    def __init__(\n",
                "        self,\n",
                "        files: List[str],\n",
                "        labels: List[int],\n",
                "        img_size: int,\n",
                "        two_crops: bool,\n",
                "        augment: bool,\n",
                "        preloaded_images=None,\n",
                "    ):\n",
                "        self.files = files\n",
                "        self.labels = labels\n",
                "        self.img_size = img_size\n",
                "        self.two_crops = two_crops\n",
                "        self.augment = augment\n",
                "\n",
                "        if preloaded_images is not None:\n",
                "            self.images = preloaded_images\n",
                "        else:\n",
                "            self.images = [None] * len(self.files)\n",
                '            print(f"⚡ Loading {len(files)} images into RAM...")\n',
                "\n",
                "            with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:\n",
                "                list(tqdm(executor.map(self._load_file, range(len(files))), total=len(files), leave=False))\n",
                "\n",
                "        if self.augment:\n",
                "            aug = transforms.RandomChoice([\n",
                "                transforms.Lambda(lambda x: x),\n",
                "                transforms.Lambda(lambda x: torch.rot90(x, 1, [1, 2])),\n",
                "                transforms.Lambda(lambda x: torch.rot90(x, 2, [1, 2])),\n",
                "                transforms.Lambda(lambda x: torch.rot90(x, 3, [1, 2])),\n",
                "            ])\n",
                "        else:\n",
                "            aug = transforms.Lambda(lambda x: x)\n",
                "\n",
                "        self.transform = transforms.Compose([\n",
                "            aug,\n",
                "            SafeInstanceNormalize(threshold=0.01),\n",
                "        ])\n",
                "\n",
                "    def _load_file(self, idx: int):\n",
                "        filepath = self.files[idx]\n",
                "        try:\n",
                "            img = cv2.imread(filepath, cv2.IMREAD_UNCHANGED)\n",
                "            validate_uint16_rgb_128(img, filepath, self.img_size)\n",
                "            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
                "            self.images[idx] = img  # keep uint16 in RAM\n",
                "        except Exception as e:\n",
                "            log_skip(filepath, e)\n",
                "            self.images[idx] = None\n",
                "\n",
                "    def __len__(self):\n",
                "        return len(self.files)\n",
                "\n",
                "    def __getitem__(self, idx: int):\n",
                "        img = self.images[idx]\n",
                "        if img is None:\n",
                "            return None\n",
                "\n",
                "        label = int(self.labels[idx])\n",
                "\n",
                "        img = img.astype(np.float32) / 65535.0  # HWC float32\n",
                "        img_tensor = torch.from_numpy(img).permute(2, 0, 1)  # CHW\n",
                "\n",
                "        if self.two_crops:\n",
                "            v1 = self.transform(img_tensor)\n",
                "            v2 = self.transform(img_tensor)\n",
                "            return v1, v2, torch.tensor(label, dtype=torch.long)\n",
                "        else:\n",
                "            x = self.transform(img_tensor)\n",
                "            return x, torch.tensor(label, dtype=torch.long)\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# 3. Data Manager\n",
                "# ==============================================================================\n",
                "def save_split_info(files, labels, save_dir, filename):\n",
                "    path = os.path.join(save_dir, filename)\n",
                '    with open(path, "w", newline="") as f:\n',
                "        writer = csv.writer(f)\n",
                '        writer.writerow(["filepath", "label"])\n',
                "        for fp, lb in zip(files, labels):\n",
                "            writer.writerow([fp, lb])\n",
                '    logger.info(f"Saved split info to {path}")\n',
                "\n",
                "\n",
                "def get_dataloaders(args):\n",
                '    class_map = {"Control": 0, "SNCA": 1, "GBA": 2, "PINK1": 3}\n',
                "    all_files, all_labels, stratify_labels = [], [], []\n",
                "    stratify_counter = 0\n",
                "\n",
                '    num_control_lines = len(DEFAULT_DATA_ROOTS["Control"])\n',
                "    target_per_control_line = args.max_samples // num_control_lines\n",
                "\n",
                '    logger.info("Processing Data Distribution...")\n',
                "\n",
                "    for class_name, paths in DEFAULT_DATA_ROOTS.items():\n",
                "        label = class_map[class_name]\n",
                "\n",
                '        if class_name == "Control":\n',
                "            for line_idx, line_path in enumerate(paths):\n",
                '                files = glob.glob(os.path.join(line_path, "**/*.[tT][iI][fF]*"), recursive=True)\n',
                "                files.sort()\n",
                "                random.shuffle(files)\n",
                "                files = files[: min(len(files), target_per_control_line)]\n",
                "\n",
                '                logger.info(f"  [{class_name} Line {line_idx+1}] Count: {len(files)}")\n',
                "                all_files.extend(files)\n",
                "                all_labels.extend([label] * len(files))\n",
                "                stratify_labels.extend([stratify_counter] * len(files))\n",
                "                stratify_counter += 1\n",
                "        else:\n",
                "            files = []\n",
                "            for p in paths:\n",
                '                files.extend(glob.glob(os.path.join(p, "**/*.[tT][iI][fF]*"), recursive=True))\n',
                "            files.sort()\n",
                "            random.shuffle(files)\n",
                "            files = files[: min(len(files), args.max_samples)]\n",
                "\n",
                '            logger.info(f"  [{class_name}] Count: {len(files)}")\n',
                "            all_files.extend(files)\n",
                "            all_labels.extend([label] * len(files))\n",
                "            stratify_labels.extend([stratify_counter] * len(files))\n",
                "            stratify_counter += 1\n",
                "\n",
                "    X_temp, X_test, y_temp, y_test, strat_temp, strat_test = train_test_split(\n",
                "        all_files, all_labels, stratify_labels,\n",
                "        test_size=args.test_ratio, random_state=args.seed, stratify=stratify_labels\n",
                "    )\n",
                "    X_train, X_val, y_train, y_val, _, _ = train_test_split(\n",
                "        X_temp, y_temp, strat_temp,\n",
                "        test_size=args.val_ratio, random_state=args.seed, stratify=strat_temp\n",
                "    )\n",
                "\n",
                "    os.makedirs(args.save_dir, exist_ok=True)\n",
                '    save_split_info(X_train, y_train, args.save_dir, "train_split.csv")\n',
                '    save_split_info(X_val, y_val, args.save_dir, "val_split.csv")\n',
                '    save_split_info(X_test, y_test, args.save_dir, "test_split.csv")\n',
                "\n",
                '    logger.info(f"Split -> Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")\n',
                "\n",
                "    # Train: two crops + aug\n",
                "    train_ds = InMemorySixteenBitDataset(X_train, y_train, args.img_size, two_crops=True, augment=True)\n",
                "\n",
                "    # Val: two crops + NO aug (loss monitoring 안정화)\n",
                "    val_ds = InMemorySixteenBitDataset(\n",
                "        X_val, y_val, args.img_size, two_crops=True, augment=False\n",
                "    )\n",
                "\n",
                "    g = torch.Generator()\n",
                "    g.manual_seed(args.seed)\n",
                "\n",
                "    NUM_WORKERS = 0\n",
                "\n",
                "    train_loader = DataLoader(\n",
                "        train_ds,\n",
                "        batch_size=args.batch_size,\n",
                "        shuffle=True,\n",
                "        num_workers=NUM_WORKERS,\n",
                "        pin_memory=True,\n",
                "        worker_init_fn=seed_worker,\n",
                "        generator=g,\n",
                "        collate_fn=collate_skip_none,\n",
                "        drop_last=True,\n",
                "    )\n",
                "\n",
                "    val_loader = DataLoader(\n",
                "        val_ds,\n",
                "        batch_size=args.batch_size,\n",
                "        shuffle=False,\n",
                "        num_workers=NUM_WORKERS,\n",
                "        pin_memory=True,\n",
                "        worker_init_fn=seed_worker,\n",
                "        generator=g,\n",
                "        collate_fn=collate_skip_none,\n",
                "        drop_last=True,\n",
                "    )\n",
                "\n",
                "    return train_loader, val_loader\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# 4. Model\n",
                "# ==============================================================================\n",
                "class Encoder(nn.Module):\n",
                "    def __init__(self):\n",
                "        super().__init__()\n",
                "        self.layer1 = nn.Sequential(weight_norm(nn.Conv2d(3, 64, 3, 2, 1)), nn.ReLU())\n",
                "        self.layer2 = nn.Sequential(weight_norm(nn.Conv2d(64, 128, 3, 1, 1)), nn.ReLU())\n",
                "        self.layer3 = nn.Sequential(weight_norm(nn.Conv2d(128, 256, 3, 1, 2, dilation=2)), nn.ReLU())\n",
                "        self.layer4 = nn.Sequential(weight_norm(nn.Conv2d(256, 512, 3, 1, 4, dilation=4)), nn.ReLU())\n",
                "        self.layer5 = nn.Sequential(weight_norm(nn.Conv2d(512, 1024, 3, 1, 2, dilation=2)), nn.ReLU())\n",
                "        self.gap = nn.AdaptiveAvgPool2d((1, 1))\n",
                "\n",
                "    def forward(self, x, return_map=False):\n",
                "        x = self.layer1(x)\n",
                "        x = self.layer2(x)\n",
                "        x = self.layer3(x)\n",
                "        x = self.layer4(x)\n",
                "        feat_map = self.layer5(x)\n",
                "        pooled = self.gap(feat_map).view(feat_map.size(0), -1)\n",
                "        return (pooled, feat_map) if return_map else pooled\n",
                "\n",
                "\n",
                "class SupConModel(nn.Module):\n",
                "    def __init__(self, embed_dim=512):\n",
                "        super().__init__()\n",
                "        self.encoder = Encoder()\n",
                "        self.projector = nn.Sequential(\n",
                "            weight_norm(nn.Linear(1024, 1024)), nn.ReLU(),\n",
                "            weight_norm(nn.Linear(1024, embed_dim))\n",
                "        )\n",
                "\n",
                "    def forward(self, x):\n",
                "        pooled = self.encoder(x, return_map=False)\n",
                "        return F.normalize(self.projector(pooled), dim=1)\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# 5. Training\n",
                "# ==============================================================================\n",
                "class Trainer:\n",
                "    def __init__(self, args, model, train_loader, val_loader):\n",
                "        self.args = args\n",
                "        self.model = model\n",
                "        self.train_loader = train_loader\n",
                "        self.val_loader = val_loader\n",
                "\n",
                "        self.criterion = losses.SupConLoss(temperature=args.temp)\n",
                "        self.optimizer = optim.AdamW(model.parameters(), lr=args.lr)\n",
                "        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(self.optimizer, T_max=args.epochs)\n",
                '        self.scaler = torch.amp.GradScaler("cuda", enabled=torch.cuda.is_available())\n',
                '        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n',
                "\n",
                '        self.best_loss = float("inf")\n',
                "        self.patience_counter = 0\n",
                "\n",
                "    def train_epoch(self, epoch: int):\n",
                "        self.model.train()\n",
                "        total_loss = 0.0\n",
                "        steps = 0\n",
                "\n",
                '        pbar = tqdm(self.train_loader, desc=f"Train E{epoch}/{self.args.epochs}", leave=True)\n',
                "        for batch in pbar:\n",
                "            if batch is None:\n",
                "                continue\n",
                "            view1, view2, labels = batch\n",
                "            if labels.numel() < 2:\n",
                "                continue\n",
                "\n",
                "            view1 = view1.to(self.device, non_blocking=True)\n",
                "            view2 = view2.to(self.device, non_blocking=True)\n",
                "            labels = labels.to(self.device, non_blocking=True)\n",
                "\n",
                "            images = torch.cat([view1, view2], dim=0)\n",
                "            labels2 = torch.cat([labels, labels], dim=0)\n",
                "\n",
                "            self.optimizer.zero_grad(set_to_none=True)\n",
                "\n",
                "            with torch.amp.autocast(device_type=self.device.type, enabled=torch.cuda.is_available()):\n",
                "                embeddings = self.model(images)\n",
                "                loss = self.criterion(embeddings, labels2)\n",
                "\n",
                "            self.scaler.scale(loss).backward()\n",
                "            self.scaler.step(self.optimizer)\n",
                "            self.scaler.update()\n",
                "\n",
                "            cur = float(loss.item())\n",
                "            total_loss += cur\n",
                "            steps += 1\n",
                '            pbar.set_postfix({"loss": f"{cur:.4f}"})\n',
                "\n",
                "        return 0.0 if steps == 0 else total_loss / steps\n",
                "\n",
                "    def validate(self, epoch: int):\n",
                "        self.model.eval()\n",
                "        total_loss = 0.0\n",
                "        steps = 0\n",
                "\n",
                '        pbar = tqdm(self.val_loader, desc=f"Val   E{epoch}/{self.args.epochs}", leave=True)\n',
                "        with torch.no_grad():\n",
                "            for batch in pbar:\n",
                "                if batch is None:\n",
                "                    continue\n",
                "                view1, view2, labels = batch\n",
                "                if labels.numel() < 2:\n",
                "                    continue\n",
                "\n",
                "                view1 = view1.to(self.device, non_blocking=True)\n",
                "                view2 = view2.to(self.device, non_blocking=True)\n",
                "                labels = labels.to(self.device, non_blocking=True)\n",
                "\n",
                "                images = torch.cat([view1, view2], dim=0)\n",
                "                labels2 = torch.cat([labels, labels], dim=0)\n",
                "\n",
                "                with torch.amp.autocast(device_type=self.device.type, enabled=torch.cuda.is_available()):\n",
                "                    embeddings = self.model(images)\n",
                "                    loss = self.criterion(embeddings, labels2)\n",
                "\n",
                "                cur = float(loss.item())\n",
                "                total_loss += cur\n",
                "                steps += 1\n",
                '                pbar.set_postfix({"val_loss": f"{cur:.4f}"})\n',
                "\n",
                "        return 0.0 if steps == 0 else total_loss / steps\n",
                "\n",
                "    def run(self):\n",
                '        logger.info(f"Starting Training on {self.device}")\n',
                "        os.makedirs(self.args.save_dir, exist_ok=True)\n",
                '        save_path = os.path.join(self.args.save_dir, "best_model.pt")\n',
                "\n",
                "        for epoch in range(1, self.args.epochs + 1):\n",
                "            # epoch 시작을 명시적으로 출력 (tqdm에 안 묻히게)\n",
                '            tqdm.write(f"\\n===== Epoch {epoch}/{self.args.epochs} =====")\n',
                "\n",
                "            train_loss = self.train_epoch(epoch)\n",
                "            val_loss = self.validate(epoch)\n",
                "\n",
                '            tqdm.write(f"Epoch {epoch:03d} | Train: {train_loss:.4f} | Val: {val_loss:.4f}")\n',
                "\n",
                "            if val_loss < self.best_loss:\n",
                "                self.best_loss = val_loss\n",
                "                self.patience_counter = 0\n",
                "                torch.save(self.model.state_dict(), save_path)\n",
                '                tqdm.write(f"  -> Saved Best Model (best_val={val_loss:.6f})")\n',
                "            else:\n",
                "                self.patience_counter += 1\n",
                '                tqdm.write(f"  -> No improvement (best_val={self.best_loss:.6f}) [{self.patience_counter}/{self.args.patience}]")\n',
                "                if self.patience_counter >= self.args.patience:\n",
                '                    tqdm.write("Early Stopping Triggered")\n',
                "                    break\n",
                "\n",
                "            self.scheduler.step()\n",
                "\n",
                "\n",
                "# ==============================================================================\n",
                "# Main\n",
                "# ==============================================================================\n",
                'if __name__ == "__main__":\n',
                "    args = get_args()\n",
                "    set_seed(args.seed)\n",
                "\n",
                "    train_dl, val_dl = get_dataloaders(args)\n",
                "\n",
                '    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n',
                "    model = SupConModel(embed_dim=args.embed_dim).to(device)\n",
                "\n",
                "    trainer = Trainer(args, model, train_dl, val_dl)\n",
                "    trainer.run()",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": null,
            "id": "039ba3d9",
            "metadata": {"vscode": {"languageId": "plaintext"}},
            "outputs": [],
            "source": [],
        },
    ],
    "metadata": {"language_info": {"name": "python"}},
    "nbformat": 4,
    "nbformat_minor": 5,
}
