import argparse
import glob
import os
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# "Results are reported as \(\text{mean} \pm \text{standard deviation}\) across 8 random seeds
# (where the score of each seed is the average of its inner products). 내적 평균의 경우

# --- 일러스트레이터 편집 최적화 설정 ---
plt.rcParams["svg.fonttype"] = (
    "none"  # SVG 저장 시 텍스트를 패스로 변환하지 않고 텍스트 형태로 유지
)
plt.rcParams["pdf.fonttype"] = 42  # TrueType 폰트로 저장 (가장 추천)
plt.rcParams["ps.fonttype"] = 42  # PostScript 출력도 함께 표준화
# Arial이 없을 경우 코랩 기본 폰트(Liberation Sans 등)로 자동 대체하여 폰트 경고 방지
plt.rcParams["font.family"] = "sans-serif"
plt.rcParams["font.sans-serif"] = [
    "Arial",
    "Liberation Sans",
    "DejaVu Sans",
    "sans-serif",
]
plt.rcParams["axes.unicode_minus"] = False  # 마이너스 기호 깨짐 방지


def main():
    parser = argparse.ArgumentParser(
        description="Plot SAE Pareto Frontiers (L0 vs FVU, L0 vs Acc)."
    )
    parser.add_argument(
        "--base_dir",
        type=str,
        default="/content/drive/MyDrive/Final_paper/lambda_labs_moco_only",
        help="Base directory containing MoCo_seed* folders",
    )
    parser.add_argument(
        "--linear_probe_csv",
        type=str,
        default="/content/drive/MyDrive/Final_paper/lambda_labs_moco_only/caches_per_image_centering/L0_FVU_linear_classification_chaces/unified_sae_linear_probe_results.csv",
        help="CSV file from step18_eval_probe_from_cache.py",
    )
    parser.add_argument(
        "--cnn_baseline_csv",
        type=str,
        default="/content/drive/MyDrive/Final_paper/lambda_labs_moco_only/linear_eval_moco/linear_eval_results.csv",
        help="CSV file from linear_eval.py for CNN baseline accuracy",
    )
    parser.add_argument(
        "--save_dir",
        type=str,
        default="/content/drive/MyDrive/Final_paper/lambda_labs_moco_only/caches_per_image_centering/L0_FVU_linear_classification_chaces",
        help="Directory to save the plots and aggregated csv",
    )
    parser.add_argument(
        "--disentanglement_csv",
        type=str,
        default="/content/drive/MyDrive/Final_paper/lambda_labs_moco_only/caches_per_image_centering/disentanglement/disentanglement_results.csv",
        help="Path to disentanglement_results.csv generated by step17",
    )
    parser.add_argument(
        "--erank_dir",
        type=str,
        default="/content/drive/MyDrive/Final_paper/lambda_labs_moco_only/caches_per_image_centering/erank",
        help="Directory containing effective rank JSON files",
    )

    # Colab(Jupyter) 환경에서 셀 실행 시 발생하는 argument 에러 방지
    import sys

    if "ipykernel" in sys.modules:
        args, _ = parser.parse_known_args(args=[])
    else:
        args, _ = parser.parse_known_args()

    # 1. Load True L0 and FVU from all_experiments_summary.csv (Preferred)
    # 폴더 구조: base_dir / MoCo_seed42 / SAE_dim... / all_experiments_summary.csv
    pattern_summary = os.path.join(
        args.base_dir, "*", "*", "all_experiments_summary.csv"
    )
    summary_files = glob.glob(pattern_summary)

    data_logs = []

    if summary_files:
        print(
            f"🔍 Found {len(summary_files)} all_experiments_summary.csv files. Extracting true L0..."
        )
        for sum_file in summary_files:
            # Extract CNN_Seed from directory name
            match = re.search(r"(?:MoCo_seed|seed|CNN_seed)(\d+)", sum_file)
            cnn_seed = int(match.group(1)) if match else 42

            # Extract Dim and Lambda from path just in case they are missing from CSV
            dim_match = re.search(r"SAE_dim(\d+)", sum_file)
            lam_match = re.search(r"lambda(\d+)", sum_file)
            dim_path = int(dim_match.group(1)) if dim_match else 0
            lam_path = int(lam_match.group(1)) if lam_match else 0

            try:
                df_sum = pd.read_csv(sum_file)
                for _, row in df_sum.iterrows():
                    if "layer" in df_sum.columns:
                        pass  # Removed refine_out filter to allow stage5_out and other layers

                    data_logs.append(
                        {
                            "CNN_Seed": cnn_seed,
                            "Dimension": int(row.get("d_sae", dim_path)),
                            "Lambda": int(row.get("sparsity", lam_path)),
                            "L0": float(row.get("mean_concepts_per_token", np.nan)),
                            "FVU": float(row.get("fvu", np.nan)),
                            "Test_Acc_Summary": float(
                                row.get("probe_test_acc_standard", np.nan)
                            ),
                        }
                    )
            except Exception as e:
                print(f"Error reading {sum_file}: {e}")
    else:
        print(
            f"🔍 all_experiments_summary.csv not found! Falling back to trainlog.csv (L1 Sparsity Loss instead of true L0)..."
        )
        pattern_trainlog = os.path.join(args.base_dir, "*", "*", "*_trainlog.csv")
        csv_files = glob.glob(pattern_trainlog)

        for csv_file in csv_files:
            match = re.search(
                r"(?:MoCo_seed|seed|CNN_seed)(\d+).*?SAE_dim(\d+)_lambda(\d+)", csv_file
            )
            if not match:
                continue
            cnn_seed = int(match.group(1))
            dim = int(match.group(2))
            lam = int(match.group(3))

            try:
                df = pd.read_csv(csv_file)
                if len(df) == 0:
                    continue
                last_row = df.iloc[-1]
                data_logs.append(
                    {
                        "CNN_Seed": cnn_seed,
                        "Dimension": dim,
                        "Lambda": lam,
                        "L0": last_row.get(
                            "test_sparsity", np.nan
                        ),  # This is L1 Loss, not true L0
                        "FVU": last_row.get("test_fvu", np.nan),
                    }
                )
            except:
                pass

    df_logs = pd.DataFrame(data_logs)

    # 2. Load Linear Probe Accuracy
    linear_csv_path = (
        os.path.join(args.save_dir, args.linear_probe_csv)
        if not os.path.isabs(args.linear_probe_csv)
        else args.linear_probe_csv
    )
    if os.path.exists(linear_csv_path):
        df_acc = pd.read_csv(linear_csv_path)

        # If the CSV has a 'File' column but missing CNN_Seed/Dimension/Lambda, extract them
        if "File" in df_acc.columns:
            for idx, row in df_acc.iterrows():
                fpath = str(row["File"])
                if row.get("CNN_Seed", -1) == -1 or pd.isna(row.get("CNN_Seed")):
                    m = re.search(r"(?:MoCo_seed|seed|CNN_seed)(\d+)", fpath)
                    if m:
                        df_acc.at[idx, "CNN_Seed"] = int(m.group(1))

                if (
                    "cnn_gap" in fpath
                    or "proxy" in fpath.lower()
                    or (row.get("Dimension", -1) == -1)
                ):
                    # CNN Proxy file
                    if "SAE_dim" not in fpath:
                        df_acc.at[idx, "Dimension"] = 600
                        df_acc.at[idx, "Lambda"] = 50
    elif os.path.exists(args.linear_probe_csv):
        df_acc = pd.read_csv(args.linear_probe_csv)
        if "File" in df_acc.columns:
            for idx, row in df_acc.iterrows():
                fpath = str(row["File"])
                if row.get("CNN_Seed", -1) == -1 or pd.isna(row.get("CNN_Seed")):
                    m = re.search(r"(?:MoCo_seed|seed|CNN_seed)(\d+)", fpath)
                    if m:
                        df_acc.at[idx, "CNN_Seed"] = int(m.group(1))
                if (
                    "cnn_gap" in fpath
                    or "proxy" in fpath.lower()
                    or (row.get("Dimension", -1) == -1)
                ):
                    if "SAE_dim" not in fpath:
                        df_acc.at[idx, "Dimension"] = 600
                        df_acc.at[idx, "Lambda"] = 50
    else:
        print(f"Warning: {args.linear_probe_csv} not found. Test_Acc will be NaN.")
        df_acc = pd.DataFrame(columns=["CNN_Seed", "Dimension", "Lambda", "Test_Acc"])

    if df_logs.empty:
        print("No trainlog data found!")
        return

    # 3. Merge Data
    if not df_acc.empty:
        df_merged = pd.merge(
            df_logs, df_acc, on=["CNN_Seed", "Dimension", "Lambda"], how="left"
        )
        # if Test_Acc is missing in df_acc, try to use Test_Acc_Summary
        if "Test_Acc_Summary" in df_merged.columns:
            df_merged["Test_Acc"] = df_merged["Test_Acc"].fillna(
                df_merged["Test_Acc_Summary"]
            )
    else:
        df_merged = df_logs.copy()
        if "Test_Acc_Summary" in df_merged.columns:
            df_merged["Test_Acc"] = df_merged["Test_Acc_Summary"]
        else:
            df_merged["Test_Acc"] = np.nan

    df_merged.to_csv(
        os.path.join(args.save_dir, "aggregated_sae_pareto_metrics.csv"), index=False
    )
    print("Merged data saved to aggregated_sae_pareto_metrics.csv")

    # 3.5. Load Welch Bound / Disentanglement Results for N_Alive (Alive Neurons)
    # Check if the path is provided directly, otherwise try base_dir/disentanglement
    welch_csv_path = args.disentanglement_csv
    if not os.path.exists(welch_csv_path):
        # Fallback to searching in save_dir just in case
        fallback_path = os.path.join(args.save_dir, "disentanglement_results.csv")
        if os.path.exists(fallback_path):
            welch_csv_path = fallback_path

    if os.path.exists(welch_csv_path):
        print(f"✅ Found disentanglement_results.csv at: {welch_csv_path}")
        df_welch = pd.read_csv(welch_csv_path)
        # [DEBUG CODE START] 나중에 지우기 쉽게 표시
        print("\n=== DEBUG: df_welch columns ===")
        print(df_welch.columns.tolist())
        print("=== DEBUG END ===\n")

        cols_to_merge = ["CNN_Seed", "Dimension", "Lambda", "Mean_IP"]
        if "N_Alive" not in df_merged.columns:
            cols_to_merge.append("N_Alive")
        if "Mean_IP" not in df_welch.columns:
            cols_to_merge.remove("Mean_IP")

        df_merged = pd.merge(
            df_merged,
            df_welch[cols_to_merge],
            on=["CNN_Seed", "Dimension", "Lambda"],
            how="left",
        )
    else:
        if "N_Alive" not in df_merged.columns:
            df_merged["N_Alive"] = np.nan

    # 3.7. Load ERank results (for Trend Plot only)
    erank_data = []
    if os.path.exists(args.erank_dir):
        import json

        pattern_erank = os.path.join(
            args.erank_dir, "**", "effective_rank_results.json"
        )
        for jpath in glob.glob(pattern_erank, recursive=True):
            parts = jpath.replace("\\", "/").split("/")
            config_part = None
            seed_part = None
            cnn_layer = None
            for p in parts:
                if p.startswith("SAE_d") and "_lam" in p:
                    config_part = p
                if p in ["stage5_out", "stage5_mid", "refine_out"]:
                    cnn_layer = p
                if p.isdigit() and len(p) <= 3:
                    seed_part = int(p)

            # Load the JSON
            try:
                with open(jpath, "r") as f:
                    jdata = json.load(f)

                condition_eranks = {}
                for res in jdata.get("results", []):
                    cond = res.get("condition", "unknown")
                    if cond not in condition_eranks:
                        condition_eranks[cond] = []
                    condition_eranks[cond].append(res["erank"])
            except:
                continue

            for cond, eranks in condition_eranks.items():
                val = np.mean(eranks)
                if config_part and seed_part is not None:
                    m = re.match(r"SAE_d(\d+)_lam(\d+)", config_part)
                    if m:
                        dim = int(m.group(1))
                        lam = int(m.group(2))
                        erank_data.append(
                            {
                                "Model": "SAE",
                                "CNN_Seed": seed_part,
                                "Dimension": dim,
                                "Lambda": lam,
                                "Condition": cond,
                                "ERank": val,
                            }
                        )
                elif cnn_layer and seed_part is not None:
                    # We mainly want stage5_out for comparison
                    if cnn_layer == "stage5_out":
                        erank_data.append(
                            {
                                "Model": "CNN",
                                "CNN_Seed": seed_part,
                                "Dimension": 0,  # Placeholder
                                "Lambda": 0,
                                "Condition": cond,
                                "ERank": val,
                            }
                        )

    df_erank_all = pd.DataFrame(erank_data) if erank_data else pd.DataFrame()

    # 3.8. Clean up ghost artifacts (Dimension=0 means path parsing failed & no d_sae in CSV)
    df_merged = df_merged[df_merged["Dimension"].astype(float) > 0].copy()

    # [DEBUG CODE START]
    print("\n=== DEBUG: df_merged check before plotting ===")
    print(f"Total rows in df_merged: {len(df_merged)}")
    print("Unique Dimensions:", df_merged["Dimension"].unique())
    print("Unique Lambdas:", df_merged["Lambda"].unique())

    df_dim_debug = df_merged[df_merged["Lambda"].astype(float) == 800.0]
    print(f"Rows with Lambda == 800.0: {len(df_dim_debug)}")
    print("=== DEBUG END ===\n")

    # 4. Plotting Function for Pareto Frontiers (Split into two)
    def plot_pareto_fixed_lambda(df, y_col, y_label, ax, title):
        # --- Line 1: Fixed Lambda = 800 ---
        df_dim = df[(df["Lambda"].astype(float) == 800.0)].copy()
        if not df_dim.empty:
            mean_dim = (
                df_dim.groupby("Dimension")
                .mean(numeric_only=True)
                .reset_index()
                .sort_values(by="L0")
            )
            std_dim = df_dim.groupby("Dimension").std(numeric_only=True).reset_index()

            ax.plot(
                mean_dim["L0"],
                mean_dim[y_col],
                color="gray",
                linestyle="--",
                linewidth=1.5,
                zorder=1,
                label="Trend: Fixed Lambda=800",
            )

            unique_dims = sorted(df_dim["Dimension"].unique())
            palette_dim = sns.color_palette("tab10", n_colors=len(unique_dims))

            for i, dim_val in enumerate(unique_dims):
                sub_df = df_dim[df_dim["Dimension"] == dim_val]
                c = palette_dim[i]

                ax.scatter(
                    sub_df["L0"],
                    sub_df[y_col],
                    color=c,
                    alpha=0.3,
                    marker="o",
                    zorder=2,
                )

                m_row = mean_dim[mean_dim["Dimension"] == dim_val].iloc[0]
                s_row = std_dim[std_dim["Dimension"] == dim_val].iloc[0]
                ax.errorbar(
                    m_row["L0"],
                    m_row[y_col],
                    xerr=s_row["L0"],
                    yerr=s_row[y_col],
                    fmt="o",
                    color=c,
                    capsize=4,
                    zorder=3,
                    markersize=8,
                    markeredgecolor="black",
                )

                ax.text(
                    m_row["L0"],
                    m_row[y_col],
                    f" d={int(dim_val)}",
                    color=c,
                    fontsize=11,
                    fontweight="bold",
                    verticalalignment="bottom",
                )

        # --- CNN Proxy (d=600, lambda=50) ---
        df_proxy = df[
            (df["Dimension"].astype(float) == 600.0)
            & (df["Lambda"].astype(float) == 50.0)
        ].copy()
        if not df_proxy.empty:
            mean_p = df_proxy.mean(numeric_only=True)
            std_p = df_proxy.std(numeric_only=True)

            ax.scatter(
                df_proxy["L0"],
                df_proxy[y_col],
                color="green",
                alpha=0.4,
                marker="*",
                zorder=2,
            )
            ax.errorbar(
                mean_p["L0"],
                mean_p[y_col],
                xerr=std_p["L0"],
                yerr=std_p[y_col],
                fmt="*",
                color="green",
                capsize=5,
                zorder=4,
                markersize=15,
                markeredgecolor="black",
                label="CNN Proxy (d=600, λ=50)",
            )
            ax.text(
                mean_p["L0"],
                mean_p[y_col],
                " Proxy",
                color="green",
                fontsize=12,
                fontweight="bold",
                zorder=5,
            )

        if df["L0"].mean() > 0.1:
            x_label_text = "L0 (Active Features per Token)"
        else:
            x_label_text = "L1 Sparsity Loss"

        ax.set_xlabel(x_label_text, fontsize=11, fontweight="bold")
        ax.set_ylabel(y_label, fontsize=11, fontweight="bold")
        ax.set_title(title, fontsize=13, fontweight="bold")
        ax.legend(loc="best", fontsize=9)
        ax.grid(True, linestyle="--", alpha=0.6, zorder=1)

        for spine in ax.spines.values():
            spine.set_edgecolor("black")
            spine.set_linewidth(1.5)

    def plot_pareto_fixed_dim(df, y_col, y_label, ax, title):
        # --- Line 2: Fixed Dimension = 4096 ---
        df_lam = df[(df["Dimension"].astype(float) == 4096.0)].copy()
        if not df_lam.empty:
            mean_lam = (
                df_lam.groupby("Lambda")
                .mean(numeric_only=True)
                .reset_index()
                .sort_values(by="L0")
            )
            std_lam = df_lam.groupby("Lambda").std(numeric_only=True).reset_index()

            ax.plot(
                mean_lam["L0"],
                mean_lam[y_col],
                color="black",
                linestyle=":",
                linewidth=1.5,
                zorder=1,
                label="Trend: Fixed d=4096",
            )

            unique_lams = sorted(df_lam["Lambda"].unique())
            palette_lam = sns.color_palette("husl", n_colors=len(unique_lams))

            for i, lam_val in enumerate(unique_lams):
                sub_df = df_lam[df_lam["Lambda"] == lam_val]
                c = palette_lam[i]

                ax.scatter(
                    sub_df["L0"],
                    sub_df[y_col],
                    color=c,
                    alpha=0.3,
                    marker="s",
                    zorder=2,
                )

                m_row = mean_lam[mean_lam["Lambda"] == lam_val].iloc[0]
                s_row = std_lam[std_lam["Lambda"] == lam_val].iloc[0]
                ax.errorbar(
                    m_row["L0"],
                    m_row[y_col],
                    xerr=s_row["L0"],
                    yerr=s_row[y_col],
                    fmt="s",
                    color=c,
                    capsize=4,
                    zorder=3,
                    markersize=8,
                    markeredgecolor="black",
                )

                ax.text(
                    m_row["L0"],
                    m_row[y_col],
                    f" λ={int(lam_val)}",
                    color=c,
                    fontsize=11,
                    fontweight="bold",
                    verticalalignment="top",
                )

        # --- CNN Proxy (d=600, lambda=50) ---
        df_proxy = df[
            (df["Dimension"].astype(float) == 600.0)
            & (df["Lambda"].astype(float) == 50.0)
        ].copy()
        if not df_proxy.empty:
            mean_p = df_proxy.mean(numeric_only=True)
            std_p = df_proxy.std(numeric_only=True)

            ax.scatter(
                df_proxy["L0"],
                df_proxy[y_col],
                color="green",
                alpha=0.4,
                marker="*",
                zorder=2,
            )
            ax.errorbar(
                mean_p["L0"],
                mean_p[y_col],
                xerr=std_p["L0"],
                yerr=std_p[y_col],
                fmt="*",
                color="green",
                capsize=5,
                zorder=4,
                markersize=15,
                markeredgecolor="black",
                label="CNN Proxy (d=600, λ=50)",
            )
            ax.text(
                mean_p["L0"],
                mean_p[y_col],
                " Proxy",
                color="green",
                fontsize=12,
                fontweight="bold",
                zorder=5,
            )

        if df["L0"].mean() > 0.1:
            x_label_text = "L0 (Active Features per Token)"
        else:
            x_label_text = "L1 Sparsity Loss"

        ax.set_xlabel(x_label_text, fontsize=11, fontweight="bold")
        ax.set_ylabel(y_label, fontsize=11, fontweight="bold")
        ax.set_title(title, fontsize=13, fontweight="bold")
        ax.legend(loc="best", fontsize=9)
        ax.grid(True, linestyle="--", alpha=0.6, zorder=1)

        for spine in ax.spines.values():
            spine.set_edgecolor("black")
            spine.set_linewidth(1.5)

    # 플롯 그릴 때는 Lambda=0 (스파시티 없음) 제외 (L0가 너무 커서 그래프가 망가짐)
    df_plot = df_merged[df_merged["Lambda"].astype(float) != 0.0].copy()

    # 1x4 통합 Figure 생성 (한 줄에 4개)
    fig, axes = plt.subplots(1, 4, figsize=(28, 6.5))

    plot_pareto_fixed_lambda(
        df_plot,
        "FVU",
        "Fraction of Variance Unexplained (FVU)",
        axes[0],
        "FVU (Fixed Lambda)",
    )
    plot_pareto_fixed_dim(
        df_plot,
        "FVU",
        "Fraction of Variance Unexplained (FVU)",
        axes[1],
        "FVU (Fixed Dimension)",
    )

    if "Test_Acc" in df_merged.columns and not df_merged["Test_Acc"].isna().all():
        plot_pareto_fixed_lambda(
            df_plot,
            "Test_Acc",
            "Linear Probe Accuracy (Test)",
            axes[2],
            "Accuracy (Fixed Lambda)",
        )
        plot_pareto_fixed_dim(
            df_plot,
            "Test_Acc",
            "Linear Probe Accuracy (Test)",
            axes[3],
            "Accuracy (Fixed Dimension)",
        )
    else:
        print(
            "Skipping L0 vs Acc plot because Test_Acc data is missing (Run step18 first!)."
        )
        axes[2].set_visible(False)
        axes[3].set_visible(False)

    plt.tight_layout()
    plt.subplots_adjust(wspace=0.25)

    combined_save_path = os.path.join(args.save_dir, "Pareto_Combined_1x4")
    plt.savefig(f"{combined_save_path}.svg", format="svg", bbox_inches="tight")
    plt.savefig(f"{combined_save_path}.pdf", format="pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"Saved combined 1x4 Pareto plot: Pareto_Combined_1x4.svg and .pdf")

    # 5. Draw the comprehensive Table
    def draw_table_as_svg(df, save_dir, cnn_csv):
        table_data = []

        # 1. Baseline (CNN)
        acc_str = "N/A"
        if os.path.exists(cnn_csv):
            try:
                df_base = pd.read_csv(cnn_csv)
                if "Accuracy" in df_base.columns:
                    acc_vals = df_base["Accuracy"].astype(float)
                    if acc_vals.mean() <= 1.0:
                        acc_vals = acc_vals * 100
                    acc_m, acc_s = acc_vals.mean(), acc_vals.std()
                    acc_str = f"{acc_m:.2f} ± {acc_s:.2f}"
            except Exception as e:
                print(f"Warning: Failed to load CNN baseline CSV ({e})")
        else:
            print(f"Warning: CNN baseline CSV not found at {cnn_csv}")

        table_data.append(
            ["Baseline (CNN)", "512", "-", "N/A", "512", "N/A", acc_str, "N/A"]
        )

        def format_row(name, dim, lam):
            sub = df[
                (df["Dimension"].astype(float) == float(dim))
                & (df["Lambda"].astype(float) == float(lam))
            ]
            if sub.empty:
                return None
            l0_m, l0_s = sub["L0"].mean(), sub["L0"].std()
            alive_m, alive_s = sub["N_Alive"].mean(), sub["N_Alive"].std()
            fvu_m, fvu_s = sub["FVU"].mean(), sub["FVU"].std()

            # --- [수정 구간] Test_Acc 백분율(%) 변환 로직 추가 ---
            acc_vals = sub["Test_Acc"].astype(float)
            if not acc_vals.empty and acc_vals.mean() <= 1.0:
                acc_vals = acc_vals * 100
            acc_m, acc_s = acc_vals.mean(), acc_vals.std()
            # --------------------------------------------------

            ip_m, ip_s = (
                (sub["Mean_IP"].mean(), sub["Mean_IP"].std())
                if "Mean_IP" in sub.columns
                else (np.nan, np.nan)
            )

            return [
                name,
                f"{int(dim)}",
                f"{int(lam)}",
                f"{l0_m:.1f} ± {l0_s:.1f}",
                f"{alive_m:.1f} ± {alive_s:.1f}" if not pd.isna(alive_m) else "N/A",
                f"{fvu_m:.4f} ± {fvu_s:.4f}" if not pd.isna(fvu_m) else "N/A",
                f"{acc_m:.2f} ± {acc_s:.2f}" if not pd.isna(acc_m) else "N/A",
                f"{ip_m:.3f} ± {ip_s:.3f}" if not pd.isna(ip_m) else "N/A",
            ]

        r = format_row("CNN Proxy", 600, 50)
        if r:
            table_data.append(r)

        table_data.append(["", "", "", "", "", "", "", ""])
        table_data.append(
            ["Effect of Dictionary Expansion (Fixed λ=800)", "", "", "", "", "", "", ""]
        )

        for d in [1024, 2048, 4096, 8192]:
            r = format_row("Gated SAE", d, 800)
            if r:
                table_data.append(r)

        table_data.append(["", "", "", "", "", "", "", ""])
        table_data.append(
            ["Effect of Sparsity Penalty (Fixed Dim=4096)", "", "", "", "", "", "", ""]
        )

        for l in [0, 200, 800, 3200]:
            r = format_row("Gated SAE", 4096, l)
            if r:
                table_data.append(r)

        if len(table_data) <= 4:
            print(
                "Warning: Not enough data to draw the SVG table. Check your dataframe."
            )
            return

        fig, ax = plt.subplots(figsize=(14, 6))
        ax.axis("tight")
        ax.axis("off")

        col_labels = [
            "Model",
            "Dimension",
            "λ",
            "L0 (Sparsity)",
            "Alive Neurons",
            "FVU",
            "Test Acc (%)",
            "Inner Product",
        ]

        table = ax.table(
            cellText=table_data, colLabels=col_labels, loc="center", cellLoc="center"
        )
        table.auto_set_font_size(False)
        table.set_fontsize(10)
        table.scale(1.2, 1.5)

        for (i, j), cell in table.get_celld().items():
            if i == 0:
                cell.set_text_props(weight="bold")
                cell.set_facecolor("#f0f0f0")
            elif len(table_data) > i - 1 and "Effect of" in str(table_data[i - 1][0]):
                cell.set_facecolor("#e0e0e0")
                cell.set_text_props(weight="bold", style="italic")
                if j == 0:
                    cell.set_text_props(ha="left")

        plt.title(
            "Performance and Disentanglement Metrics\n(Results are mean ± std across 8 random seeds)",
            fontweight="bold",
            pad=20,
        )

        plt.savefig(
            os.path.join(save_dir, "metrics_table.svg"),
            format="svg",
            bbox_inches="tight",
        )
        plt.savefig(
            os.path.join(save_dir, "metrics_table.pdf"),
            format="pdf",
            bbox_inches="tight",
        )
        plt.close()
        print(f"Saved metrics table: metrics_table.svg and .pdf")

    draw_table_as_svg(df_merged, args.save_dir, args.cnn_baseline_csv)

    def plot_erank_trend(df_erank, save_dir):
        if df_erank.empty:
            return

        # Filter for Lambda=800 or CNN
        df_sub = df_erank[
            (df_erank["Lambda"] == 800) | (df_erank["Model"] == "CNN")
        ].copy()
        if df_sub.empty:
            return

        conditions = ["raw", "pca", "norm_pca"]
        titles = {"raw": "Raw (No PCA)", "pca": "PCA 250", "norm_pca": "Std + PCA 250"}
        colors = {"raw": "#4C72B0", "pca": "#DD8452", "norm_pca": "#55A868"}

        fig, axes = plt.subplots(1, 3, figsize=(18, 5))

        # Sort dimensions correctly. CNN is 0
        df_sub = df_sub.sort_values(by="Dimension")
        dims = sorted(df_sub["Dimension"].unique())
        x_map = {d: i for i, d in enumerate(dims)}
        labels = ["CNN" if d == 0 else str(d) for d in dims]
        x_ticks = [x_map[d] for d in dims]

        for i, cond in enumerate(conditions):
            ax = axes[i]
            df_cond = df_sub[df_sub["Condition"] == cond]
            color = colors.get(cond, "gray")

            if df_cond.empty:
                ax.set_title(f"No Data for {cond}")
                ax.axis("off")
                continue

            # Plot individual points
            for d in dims:
                y_vals = df_cond[df_cond["Dimension"] == d]["ERank"].values
                if len(y_vals) > 0:
                    x_val = x_map[d]
                    ax.scatter(
                        [x_val] * len(y_vals),
                        y_vals,
                        color=color,
                        alpha=0.3,
                        s=40,
                        zorder=2,
                    )

            # Plot trend line (mean)
            means = df_cond.groupby("Dimension")["ERank"].mean().sort_index()
            x_vals = [x_map[d] for d in means.index]
            y_means = means.values

            ax.plot(
                x_vals,
                y_means,
                marker="o",
                markersize=8,
                color=color,
                linewidth=2.5,
                zorder=3,
            )

            ax.set_xticks(x_ticks)
            ax.set_xticklabels(labels)

            ax.set_xlabel("Model / SAE Dimension", fontsize=11)
            if i == 0:
                ax.set_ylabel("Effective Rank (ERank)", fontsize=11)
            ax.set_title(titles.get(cond, cond.upper()), fontsize=13, fontweight="bold")
            ax.grid(True, alpha=0.3)

        sns.despine()
        fig.suptitle(
            "ERank Trend with Increasing SAE Dimension (Fixed λ=800)",
            fontsize=15,
            fontweight="bold",
            y=1.05,
        )
        plt.tight_layout()
        save_path = os.path.join(save_dir, "ERank_Trend_Fixed_Lambda800")
        plt.savefig(f"{save_path}.svg", format="svg", bbox_inches="tight")
        plt.savefig(f"{save_path}.pdf", format="pdf", bbox_inches="tight")
        plt.close(fig)
        print(f"Saved ERank Trend plot (1x3 subplots): {save_path}.svg and .pdf")

    plot_erank_trend(df_erank_all, args.save_dir)

    # 5. Plotting Function for Trend Lines (N_Alive)
    def plot_trend(
        df, x_col, y_col, fixed_col, fixed_val, x_label, y_label, base_save_name, color
    ):
        df_sub = df[df[fixed_col] == fixed_val].copy()
        if df_sub.empty or df_sub[y_col].isna().all():
            return

        plt.figure(figsize=(10, 6))
        mean_df = (
            df_sub.groupby(x_col)
            .mean(numeric_only=True)
            .reset_index()
            .sort_values(by=x_col)
        )
        std_df = (
            df_sub.groupby(x_col)
            .std(numeric_only=True)
            .reset_index()
            .sort_values(by=x_col)
        )

        # Connect means with a subtle line
        plt.plot(
            mean_df[x_col],
            mean_df[y_col],
            color="gray",
            linestyle="--",
            linewidth=1.5,
            zorder=1,
            label=f"Trend: Fixed {fixed_col}={fixed_val}",
        )

        unique_x = sorted(df_sub[x_col].unique())
        # Use tab10 for Dimension, husl for Lambda
        palette = (
            sns.color_palette("tab10", n_colors=len(unique_x))
            if x_col == "Dimension"
            else sns.color_palette("husl", n_colors=len(unique_x))
        )
        marker_style = "o" if x_col == "Dimension" else "s"

        for i, x_val in enumerate(unique_x):
            sub_x_df = df_sub[df_sub[x_col] == x_val]
            c = palette[i]

            # Scatter seeds
            plt.scatter(
                sub_x_df[x_col],
                sub_x_df[y_col],
                color=c,
                alpha=0.3,
                marker=marker_style,
                zorder=2,
            )

            # Mean and error bar
            m_row = mean_df[mean_df[x_col] == x_val].iloc[0]
            s_row = std_df[std_df[x_col] == x_val].iloc[0]
            plt.errorbar(
                m_row[x_col],
                m_row[y_col],
                yerr=s_row[y_col],
                fmt=marker_style,
                color=c,
                capsize=4,
                zorder=3,
                markersize=8,
                markeredgecolor="black",
            )

        plt.xlabel(x_label, fontsize=12)
        plt.ylabel(y_label, fontsize=12)
        plt.title(f"{y_label} vs {x_label}", fontsize=15, fontweight="bold")
        if x_col == "Lambda":
            plt.xscale("log")  # Lambda is often logarithmic

        # --- Add CNN Proxy (d=600, Lambda=50) ---
        df_proxy = df[(df["Dimension"] == 600) & (df["Lambda"] == 50)].copy()
        if not df_proxy.empty and not df_proxy[y_col].isna().all():
            mean_p = df_proxy[y_col].mean()
            std_p = df_proxy[y_col].std()
            proxy_x = 600 if x_col == "Dimension" else 50

            sns.scatterplot(
                data=df_proxy,
                x=x_col,
                y=y_col,
                color="green",
                alpha=0.3,
                marker="*",
                zorder=2,
            )
            plt.scatter(
                [proxy_x],
                [mean_p],
                color="green",
                marker="*",
                s=200,
                label="CNN Proxy (d=600, Lambda=50)",
                zorder=4,
            )
            plt.errorbar(
                [proxy_x],
                [mean_p],
                yerr=[std_p],
                fmt="none",
                ecolor="green",
                capsize=4,
                alpha=0.7,
                zorder=2,
            )
            plt.text(
                proxy_x,
                mean_p,
                " Proxy",
                color="green",
                fontsize=10,
                fontweight="bold",
                zorder=5,
            )

        plt.legend(loc="best")
        plt.grid(True, linestyle="--", alpha=0.6, zorder=1)
        plt.tight_layout()

        plt.savefig(
            os.path.join(args.save_dir, f"{base_save_name}.svg"),
            format="svg",
            bbox_inches="tight",
        )
        plt.savefig(
            os.path.join(args.save_dir, f"{base_save_name}.pdf"),
            format="pdf",
            bbox_inches="tight",
        )
        plt.close()
        print(f"Saved plots: {base_save_name}.svg and {base_save_name}.pdf")

    # Plot N_Alive trends
    if not df_merged["N_Alive"].isna().all():
        plot_trend(
            df_merged,
            "Dimension",
            "N_Alive",
            "Lambda",
            800,
            "Dimension (d_sae)",
            "Number of Alive Neurons",
            "Trend_Alive_vs_Dimension",
            "blue",
        )
        plot_trend(
            df_merged,
            "Lambda",
            "N_Alive",
            "Dimension",
            4096,
            "Sparsity Penalty (Lambda)",
            "Number of Alive Neurons",
            "Trend_Alive_vs_Lambda",
            "red",
        )


if __name__ == "__main__":
    main()
